### ISSUE TITLE
More flexible per-app disabling.

### ISSUE THREAD

**Issue by villiansv** [thompsonate/Shifty#10]
So this was an issue with f.lux as well. The option to disable for a given app is only accessible 1. while the app is running, and 2. from the Shifty icon in the menu bar.

I ran into an issue disabling it for a game (Starcraft 2) - the game automatically runs full screen, and doesn't allow you to see the menu bar at the top. So the only way to choose this option is to run the game in windowed mode (thankfully it existed) so I could see the menu bar.

Proposed - global keyboard shortcut to toggle disable for currently running app, or an interface where you can manually add apps for it to be disabled for. Otherwise, it would be impossible to actually toggle this if the app doesn't support windowed mode.

Admittedly this may go beyond the scope of this simple (yet super useful) tool, but in case it's not too much effort, it would be great to have.

**Comment by thompsonate** [comment]
This issue is only with full screen apps that don't support macOS's full screen mode, right? Is it common for games to not support windowed mode?

**Comment by calda** [comment]
@thompsonate I do remember a good number of games that are like that (Minecraft was in that bucket). 

+1 to configurable global shortcuts for some common actions (toggle night shift, disable/enable for current app)

**Comment by thompsonate** [comment]
@calda I distinctly remember Minecraft having a windowed mode. But yeah, global shortcuts are on the future feature list. I already found a [framework](https://github.com/shpakovski/MASShortcut) that should handle that.

**Comment by villiansv** [comment]
> This issue is only with full screen apps that don't support macOS's full screen mode, right? Is it common for games to not support windowed mode?

@thompsonate I believe so, since with the default macOS full screen mode you can move the mouse to the top of the screen to get the menu bar slide into view. 

Exclusive full screen apps (which I think most games are) don't allow this (nor should they, since it would be detrimental to gameplay). Admittedly though, I've only tested it with Blizzard games and Myth 2 - and for all of them you have to go through the game's settings to run it windowed, so you can disable it for that app, and then fullscreen it again. A bit clunky.

Great to hear that shortcuts are coming in the future though.
