### ISSUE TITLE
Suggestion : change wallpaper when Night Shift is activated

### ISSUE THREAD

**Issue by nicolinuxfr** [thompsonate/Shifty#13]
Great news for the dark mode synced with Night Shift in the last version ! 

One suggestion in the same range : change the wallpaper when Night Shift is activated. That way, we could choose two backgrounds, one for the day and one less bright for the night. 

Thanks for your work.

**Comment by thompsonate** [comment]
Thanks for the suggestion and the article!

This is a good idea, just something that is a lower priority for me. If someone else would like to take this on, that would be great.

**Comment by nicolinuxfr** [comment]
No problem, I understand. :-)

And your welcome !

**Comment by maciboy** [comment]
With the dynamic wallpapers in Mojave this feature might me unnecessary now ;)

**Comment by thompsonate** [comment]
Yeah, this was never a big priority anyways. With dynamic wallpapers, I don't think adding a similar feature to Shifty would be very useful.
