### ISSUE TITLE
Bring back cool icon

### ISSUE THREAD

**Issue by calda** [thompsonate/Shifty#15]
This moon dude was so cool. Look at those sunglasses!!!!!!!

<img width="289" alt="screenshot 2017-11-02 at 1 59 07 pm" src="https://user-images.githubusercontent.com/1811727/32342182-0ad0ce40-bfd6-11e7-87f5-cf08f6c9fe19.png">

please bring him back

**Comment by thompsonate** [comment]
He won’t fit in the menu bar :/
