### ISSUE TITLE
shifty.natethomson.io/donate hangs on empty page

### ISSUE THREAD

**Issue by calda** [thompsonate/Shifty#18]
The Donate page linked from Shifty and `shifty.natethompson.io` hangs in an ambiguous state for a few seconds while it reidrects to the PayPal processing page.

![video](https://user-images.githubusercontent.com/1811727/32873383-c164441a-ca59-11e7-9536-e70bc67499ef.gif)

This has been happening constantly on my laptop, but I'm not sure how reproducible it is on other devices.

It would be useful if the `shifty.natethompson.io/donate` had feedback text, like _"Redirecting you to PayPal"._

**Comment by thompsonate** [comment]
looks like PayPal's fault
