### ISSUE TITLE
I don't understand why Shifty needs my location or even needs to control whether Night Shift is active

### ISSUE THREAD

**Issue by sn0wyfall** [thompsonate/Shifty#33]
Hey!

macOS controls when Night Shift is enabled based on the sunset/sunrise times. Shifty allows you to change the intensity or even turn it on/off conveniently, and also lets you disable for an hour, a specific time, and for a specific application. However, I don't think it should request my location and take over enabling and disabling Night Shift – I think macOS should be left to do this. 

In 0.4, I disabled scheduled Night Shift because I didn't want Shifty to take control of sunrise/sunset enabling and disabling. However, I still kept on getting the "Shifty needs your location; disable scheduling" warning.

**Comment by thompsonate** [comment]
Hi!

In certain situations, Shifty needs to know the state Night Shift should be based on the schedule. This is why it needs to be able to calculate the sunrise and sunset times based on your location. Shifty still relies on Night Shift to set its state based on the schedule. 

I don't really like using the location, but it's currently the only method I have of calculating the sunrise and sunset times. I'm working with some other people to try to figure out how to get those times from where they're stored in the system so Shifty won't need location permissions.

Thanks for your interest! Let me know if you have any more questions.

**Comment by sn0wyfall** [comment]
Huh, seems like you fixed it, right? Thanks a lot! Just FYI, I was talking about Shifty's behavior in version 0.2 I believe. It never bugged me after asking for my location (and my having declined it). That worked really well for me because I only ever used Shifty to enable/disable Night Shift and to change its intensity – I never used any of its fancy scheduling/app-disabling features. Now that it seems like you've fixed it in 0.5, thank you very much!

**Comment by thompsonate** [comment]
Yup, it's fixed! No more dealing with location. You can thank @choco for this, since he's the one who figured out how to get the times from the system.
