### ISSUE TITLE
Feature request: Sync with Hue lights?

### ISSUE THREAD

**Issue by julienma** [thompsonate/Shifty#37]
Hey!
Wouldn't it be cool if Shifty could drive Philips Hue lights, like [F.lux](https://justgetflux.com/) does (see https://www.howtogeek.com/248915/how-to-sync-f.lux-and-philips-hue-lights-for-eye-friendly-evening-lighting/)?
It could switch them on/off at the same time than Night Shift, and could even sync the lights' luminosity with Night Shift's.

Some references / related apps:

- [F.lux](https://justgetflux.com/)
- [Circadian Hue](https://itunes.apple.com/us/app/circadian-hue-for-philips-hue/id1165687051?mt=12)
- [Brilliance](http://brilliance.site/)

**Comment by thompsonate** [comment]
Does Hue not support scheduling routines at sunrise and sunset?

I think this is a little beyond the scope of Shifty at this point. However, I would like to add scripting support eventually, so you could possibly have another app that gets the Night Shift settings from Shifty and schedules the Hue lights accordingly.

**Comment by julienma** [comment]
> Does Hue not support scheduling routines at sunrise and sunset?

It does, but AFAIK it's part of their "recipe", which means you can't have more than 1 active recipe per item (e.g. if I add another recipe on some lights, it will override whatever behavior I currently have set). So having this driven by another app would override this.

Also, this would mean that the lights would change only when Shifty runs — which IMO is welcome, as it means it'll work only when I'm actually working on my laptop, and probably wanting my lights to dim as much as my screen.

If I had time to learn XCode, I'd happily try this on a fork, but, well... :)

Anyway, the scripting support would be great.
You're talking about letting Apple Script poll Shifty for some values (the way [Omnifocus supports Applescript](https://inside.omnifocus.com/applescript)), or letting Shifty run some Applescript whenever some "Shifty events" happen (bit like [Calendar can trigger applescripts](https://www.engadget.com/2013/03/18/triggering-applescripts-from-calendar-alerts-in-mountain-lion/))?

**Comment by thompsonate** [comment]
Ok, I understand the appeal now.

That's a good idea, letting Shifty trigger scripts. I might try to add that eventually.

But now that I think about it, you don't really need Shifty at all. You can just use my [CBBlueLightClient header](https://github.com/thompsonate/Shifty/blob/master/Shifty/CBBlueLightClient.h) to get the state and color temperature (CCT). And you can get notifications on Night Shift change by [registering for a notification](https://github.com/thompsonate/Shifty/blob/master/Shifty/BLNotificationBlock.m). If you do get around to doing this, I'd be happy to help with getting the info from Night Shift.

**Comment by julienma** [comment]
Thanks Nate, I'll have a look at these — sometime in the future ;)
Anyway, if you do add AppleScript support to Shifty, please let me know.

**Comment by thompsonate** [comment]
I'll make sure I do. It'll probably be a while though, since I want to release a 1.0 eventually and there's still quite a bit of work to get there.
