### ISSUE TITLE
Support installations through Homebrew

### ISSUE THREAD

**Issue by Aghassi** [thompsonate/Shifty#4]
Homebrew is a really great package manager for macOS, and it would benefit those using it to have this published as a formula there. You can read more here https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md

The main thing is that I, as a user, can get updates without having to come and download stuff again from here. Unless of course you use Sparkle to update your app. Either way, this is still a convenient way to install 😄 . I would greatly appreciate it!

Currently `brew cask search shifty` returns nothing.

**Comment by guillaumebriday** [comment]
https://github.com/caskroom/homebrew-cask/pull/37893

**Comment by Aghassi** [comment]
@guillaumebriday Appreciate it! We can close this once that issue is completed?

**Comment by thompsonate** [comment]
Thanks for taking care of it @guillaumebriday. What do I need to do once I update it to make sure the latest version is in Homebrew?
