### ISSUE TITLE
Has Shifty been tested on macOS High Sierra 10.13.4 beta? It's impossible to disable Night Shift unless Shifty is closed.

### ISSUE THREAD

**Issue by edgariscoding** [thompsonate/Shifty#41]
I'm aware that it's a beta, so issues are expected. 

But 10.13.4 will likely be released to the public very soon, would be great if the issue was fixed ahead of time.

**Comment by thompsonate** [comment]
I have not tested it in 10.13.4.

What exactly is the problem you're having? Does Night Shift just not disable at all? Does it work when you disable it via System Preferences? Are you sure this functionality is different from 10.13.3?

**Comment by edgariscoding** [comment]
The problem I'm having is, assuming Night Shift / Shifty are both enabled and the sun has gone down:

If I open the Notification Center (on trackpad, swipe with two fingers from the right) and disable Night Shift, it'll look like it's disabled but the second I switch windows or click on the desktop or anything, Night Shift will enable itself.

The same happens if instead of disabling Night Shift within macOS I disable it by clicking on Shifty and choosing to disable for an hour or whatever. 

The only way to get it to actually stay disabled is to quit Shifty.

**Comment by thompsonate** [comment]
Gotcha. I think I know what's causing this. It's due to a change I made in 0.5.1 that I made while trying to fix a different problem. [Version 0.5](https://github.com/thompsonate/Shifty/releases/tag/0.5) shouldn't have this issue.

I'm working refactoring the core logic so I don't keep causing problems by fixing other issues.

**Comment by edgariscoding** [comment]
Oh awesome, thank you!

**Comment by thompsonate** [comment]
Just released 0.5.2 which should finally fix this! Please let me know if you still have issues with it.
