### ISSUE TITLE
Feature Request: Custom color tints for shaded screen

### ISSUE THREAD

**Issue by rubyframework** [thompsonate/Shifty#45]
First off, great app! Very useful, love the simplicity.

Thought it would be neat if there were a feature allowing you to customize the colors that shade the screen? I've attached a couple photos to show an example. The photos are from a paid app - [NightTone](http://alexdenk.eu/mywork/nighttone.html) - which seems similar to Shifty. 

*notice the options to select a color, or open the color picker to choose your own.
![1](https://user-images.githubusercontent.com/21975869/38727503-099b5b10-3ec2-11e8-852c-c8cb3ecd7516.jpg)

*notice the orange tint to the shaded screen
![2](https://user-images.githubusercontent.com/21975869/38727514-1053befc-3ec2-11e8-81f8-566e13bc059f.jpg)

**Comment by choco** [comment]
This is simply not possible, Shifty uses the Night Shift functionality provided by macOS, and you can't change the color for that.
Also I want to note that what Night Shift and Night Tone achieve completely different goals. The latter just applies a "color filter window" above everything, Night Shift instead changes the monitor color profile to block the colours that are more "harmful" in low light environment for the eyes.

**Comment by rubyframework** [comment]
Ah I see... Thank you for the response and explanation!
