### ISSUE TITLE
Night Shift intensity curve status lost when switching off manually or because of rules

### ISSUE THREAD

**Issue by choco** [thompsonate/Shifty#46]
The title is long so it's kinda self explanatory XD

When looking on how to obtain the sunrise and sunset times I remember seeing something about the curve, so it may be possible to save that value and restart from that.

**Comment by thompsonate** [comment]
What exactly do you mean by intensity curve status? Do you mean the level that it's at while slowly shifting according to the schedule? I just played around with that and it works fine.

**Comment by choco** [comment]
Yes, I use Night Shift at the maximum value, and the issue is really visibile.
Steps to reproduce:
1- set night shift with sunset/sunrise schedule
2- set night shift value to max (so it's more obvious)
3- wait for night shift to kick in according to schedule
4- once enabled by schedule, manually disable and enable it

**Comment by thompsonate** [comment]
I see what you're talking about now. Is this really that much of an issue though?

The problem with restarting from the same value is that Night Shift won't be increasing it anymore. It would just stay that way. There's no easy way to achieve the functionality you're looking for. :(

**Comment by choco** [comment]
I found out that it is possible to restore the previous state of the macOS curve by disabling and reenabling the schedule instead of manually setting the enabled switch. This should probably be the default. 

You can actually check that this works by doing the same process in Preferences. Instead of manually overriding Nightshift, you toggle between the disabled schedule and the desired schedule and NightShift is enabled but still following the curve. 

This mean that instead of setting enabled here https://github.com/thompsonate/Shifty/blob/master/Shifty/NightShiftManager.swift#L136 you switch the schedule.

**Comment by choco** [comment]
Here's how I'm doing it, and it seems to work well in my testing!

``` diff
diff --git a/Shifty/NightShiftManager.swift b/Shifty/NightShiftManager.swift
index d867e98..e711b67 100644
--- a/Shifty/NightShiftManager.swift
+++ b/Shifty/NightShiftManager.swift
@@ -134,6 +134,11 @@ enum NightShiftManager {
         }
         set {
             client.setEnabled(newValue)
+            if (newValue && blueLightStatus.mode) {
+                let savedMode = blueLightStatus.mode
+                client.setMode(0)
+                client.setMode(savedMode)
+            }
         }
     }
 
```

**Comment by thompsonate** [comment]
Oh, nice! I wouldn't have expected this to work as well as it does. Thanks for the code.

**Comment by choco** [comment]
We actually need to add another condition to the if, we have to check if we are inside a schedule, because if we aren't as it is written we can't manually activate NightShift.

**Comment by thompsonate** [comment]
Oh, that makes sense. Glad you caught that.
