### ISSUE TITLE
"Turn off" only works until you switch apps

### ISSUE THREAD

**Issue by andrews05** [thompsonate/Shifty#47]
Not sure if this is intentional or not, but when night shift is on and I choose "Turn off night shift" it only stays off until I switch to another app. Even clicking on the Shifty menu again will turn it back on.

On an unrelated note, has anyone else noticed that the menu bar in dark mode is one pixel shorter than the normal one? I'm probably just OCD but it messes with my window positions when it switches.

**Comment by thompsonate** [comment]
It's unintentional. I rewrote a lot of the app a while ago but I haven't released an update yet. I'll try to release a version that'll fix this bug in the next week.

Regarding the menu bar, for some reason that's the way Apple designed it. I'm unaware of any way to change it.

**Comment by thompsonate** [comment]
Just released 0.5.2 which should finally fix this! Please let me know if you still have issues with it.
