### ISSUE TITLE
[Feature Request] True Tone Support

### ISSUE THREAD

**Issue by jtgrenz** [thompsonate/Shifty#51]
The new 2018 Macs now ship with Apple's new [_True Tone_](https://support.apple.com/en-ca/HT208909) settings similar to iOS where it detects the rooms white balance and adjust accordingly. Its actually quite pleasant and having used it for a few hours out of the box, I was basically sold on it... _except_ I can't have it on when editing photos;  colour balance gets thrown off. Thats why I like Shifty thus far; it lets me toggle off night shift when photo editing. 

True tone gives a very subtle shift to the whites and it varies room to room based on the light, so I need to leave it off because I cant tell when its shifting. 

I'm not sure if its possible to adjust the true tone the same way as night shift, but it seems related and the arguments for needing a night shift adjustment are usually the same as needing one for true tone. 

Really like the app thus far, so thanks for sharing your hard work 👍

**Comment by thompsonate** [comment]
I agree - True Tone would be a great feature addition. Wanna buy me a 2018 MacBook Pro? 😉

If I can figure out how to toggle True Tone, this should be pretty simple to implement.

**Comment by thompsonate** [comment]
I figured it out!

So as I have it right now, there's a setting that, when enabled, will disable True Tone for all apps and websites that Night Shift is disabled for, but not the timers. Does that make sense or should I reconsider?

There's also a menu item that'll let you easily toggle True Tone on and off.

**Comment by thompsonate** [comment]
The True Tone toggle is only visible on computers that support True Tone. Currently that's just the 2018 MacBook Pro. So unless you have a 2018 MBP, that's by design.

**Comment by minimum91** [comment]
@thompsonate 
Sorry, should have mentioned it right away. I have the 2018 15" MBP with True Tone.

**Comment by minimum91** [comment]
@thompsonate  Oh. "True Tone is supported by macOS 10.14 and later"

**Comment by thompsonate** [comment]
Oh, you're running 10.13.6? I forgot they shipped with that.

So IIRC the build of 10.13.6 the 2018 MBP shipped with is different than the build of 10.13.6 that other Macs got. Because they're the same version number, I'm not able to tell if the build you're running supports True Tone or not. So I had to just support the True Tone feature on 10.14.0 and higher.

If you update to Mojave, it should work fine.

**Comment by minimum91** [comment]
@thompsonate Very unfortunate for me. I will stay on High Sierra at least until next year.
