### ISSUE TITLE
Screen Wake event: Night Shift disabled but then reenabled

### ISSUE THREAD

**Issue by calda** [thompsonate/Shifty#52]
Night Shift was still on when I opened my laptop this morning. The logs seem to imply that it *was* correctly disabled, but then incorrectly reenabled:

```
[Sep 6, 2018 at 9:30:41 AM]: BLNotificationBlock called
[Sep 6, 2018 at 9:30:41 AM]: Schedule: sunSchedule
[Sep 6, 2018 at 9:30:41 AM]: Night Shift state: false
[Sep 6, 2018 at 9:30:42 AM]: Screen did wake
[Sep 6, 2018 at 9:30:53 AM]: Night Shift state: true
```

**Comment by thompsonate** [comment]
Are you running 0.5.2?

I’m sitting on a fix but hadn’t released it since nobody complained. At this point I’ll probably just include it in the release for Mojave. I can give you a binary if you or anyone else wants to test it, though.

**Comment by calda** [comment]
Looks like I was on 0.5.1 😱
