### ISSUE TITLE
Automatic Dark Mode does not work on Mojave

### ISSUE THREAD

**Issue by philihub** [thompsonate/Shifty#53]
I would like to invoke Dark Mode with the Night Shit schedule. On the latest public beta of macOS 10.14 Dark Mode is not switched on automatically.

**Comment by thompsonate** [comment]
Are you using a custom Night Shift schedule by chance? I'm able to reproduce it using the Custom schedule.

**Comment by philihub** [comment]
The custom schedule works but the sunrise to sunset setting does not invoke Dark Mode.

**Comment by thompsonate** [comment]
Huh, that's strange. I was having problems with Custom and Off, which I just fixed. Sunset to sunrise is much harder to debug, but I'll see if I can reproduce.

**Comment by partounian** [comment]
My issue is that the Quick Toggle, doesn't seem to toggle dark mode

**Comment by thompsonate** [comment]
Apparently there's a lot going wrong with the scheduled dark mode. I didn't test it enough before I released the last version.

Thanks for pointing this out!

**Comment by derekschinke** [comment]
The mode it was last on also gets stuck after it wakes from sleep. So if I go to bed with dark mode on, when I wake up, even though it's supposed to toggle during the day, it'll be stuck on dark mode before I toggle it manually.

**Comment by maciboy** [comment]
Can you please provide a Mojave .dmg build of your latest code (Mojave branch, I think^^), as the latest downloadable build is v0.5.2 in the release tab and on your webpage ;)

Thanks a lot for all the efforts!

**Comment by thompsonate** [comment]
I will, I'm just working on solving this issue and a few other things. Hoping to release an update in the next few days!

**Comment by choco** [comment]
`sunrise` and `sunset` are updated god knows when, so we have to take into account if they have been updated or not, just doing `let scheduledState = now >= sunset` isn't enough.
 For example this morning I had this in my log
```
[3 Oct 2018 at 09:12:37]: Wake from sleep notification posted
[3 Oct 2018 at 09:12:37]: sunset: 2018-10-02 16:43:04 +0000
[3 Oct 2018 at 09:12:37]: sunrise: 2018-10-03 05:14:31 +0000
[3 Oct 2018 at 09:12:37]: scheduled state: true
```
so you need to check for both sunset and sunrise with respect to the current date.

**Comment by choco** [comment]
Something like this should work
``` swift
            // For some reason, BrightnessSystemClient.isDaylight doesn't track perfectly with sunrise and sunset
            // When daylight, sunset time is previous occurence
            // When not daylight, sunset time is next occurence
            // Should return true when not daylight
            let scheduledState : Bool
            let order = NSCalendar.current.compare(sunrise, to: sunset, toGranularity: .day)
            switch order {
                case .orderedSame:
                    scheduledState = now >= sunset
                case .orderedAscending:
                    scheduledState = now >= sunset || now <= sunrise
                case .orderedDescending:
                    scheduledState = now >= sunset && now <= sunrise
            }
            logw("scheduled state: \(scheduledState)")
            return scheduledState
```

**Comment by thompsonate** [comment]
Are you having issues with the code on master? I know the latest release is broken but I thought I'd already fixed it. 

What I've seen is that the sunrise time is the day after the sunset time and both times switch over to the next day after sunset. That explains the code I'm currently using: `let scheduledState = now >= sunset`

**Comment by choco** [comment]
Yes, I had the issue with the current master. As you can see from the log from this morning above, your check doesn't work if the sunset is still set to the previous day and we are past the sunrise. It was 9 am 3 Oct, but sunset was still set to 2 Oct, and I was past the sunrise of 3 Oct (but per your check the schedule was active). The code above should cover all possible cases I think?

**Comment by thompsonate** [comment]
Ah, maybe it behaves differently in the Eastern Hemisphere (or I just didn't test it enough). I guess that's what I get for assuming that the date would always switch over by the sunrise.

Thanks for the code!

**Comment by nicolinuxfr** [comment]
The automatic switch to Dark Mode is still not working for me with 1.0 version and macOS 10.14.1. 

In the console, here's what I have : 

```
par défaut	17:11:32.446953 +0100	Shifty	System appearance change
par défaut	17:11:32.447021 +0100	Shifty	Current system appearance, (HLTB: 1), (SLS: 0)
par défaut	17:11:32.447068 +0100	Shifty	Invalidate NSApp effectiveAppearance
par défaut	17:11:32.447280 +0100	Shifty	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 0
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x600001d8d860
 (
    "<NSAquaAppearance: 0x600002b89cc0>",
    "<NSSystemAppearance: 0x600002b89d40>"
)>
```

**Comment by choco** [comment]
Can you clarify your issue? Does Night Shift turn on and off, or is only Dark mode that is not switching?
You should also post the log `~/Library/Logs/Shifty` to have more information.

**Comment by nicolinuxfr** [comment]
Night Shift is working fine, it's only the Dark Mode from Mojave that is not (de)activating along with Night Shift.

Here's the last log file : 
[Shifty-0.log](https://github.com/thompsonate/Shifty/files/2604977/Shifty-0.log)

**Comment by choco** [comment]
Does Shifty toggle Dark Mode if you set and use the corresponding shortcut?

**Comment by nicolinuxfr** [comment]
Yes, the shortcut is indeed working fine. However, the Night Shift toggle in the menu does not (de)activate Dark Mode, along with Night Shift.

**Comment by choco** [comment]
Mmmm that makes zero sense, since it's the same code for both functions....

My advice would be to completely reset Shifty (delete preferences, logs, caches, accessibility permissions; the first 3 should be in the ~/Library corresponding subdirectories; after deleting those files restart you Mac, for some reason under Mojave these files are restored if you don't perform a shutdown between deleting them and reopening the app).
Once you reset them change the preferences however you like and post a screenshot of that, then once you reproduce the issue, post again the log file, the output of the command `corebrightnessdiag nightshift-internal` and finally your timezone.
