### ISSUE TITLE
Cut new release for homebrew

### ISSUE THREAD

**Issue by dmmalam** [thompsonate/Shifty#58]
Would be cool to use the TrueTone support off master

**Comment by thompsonate** [comment]
Heh, I forgot Shifty is on Homebrew.

I'll be releasing a version with True Tone support very soon! Just have to squash a few bugs.

**Comment by dmmalam** [comment]
Awesome, looking forward to it.

**Comment by thompsonate** [comment]
I created a [pull request](https://github.com/Homebrew/homebrew-cask/pull/53075) in homebrew-cask
