### ISSUE TITLE
Different icons when on/off

### ISSUE THREAD

**Issue by villiansv** [thompsonate/Shifty#6]
I think it would be nice to have the menubar icon change depending on the on/off status of Night Shift. You could for example keep the current icon for On and have a fully white sun as Off, or alternatively current icon for Off and a moon for On.

It will go well with the quick toggle option, which I love.

Thanks for a great app!

**Comment by thompsonate** [comment]
That's a good idea. It does make sense to have a little more visual feedback with Quick Toggle since it takes a second for Night Shift to kick in.

Thanks for the suggestion!

**Comment by thompsonate** [comment]
I want to get some feedback on potential icons. Here's two I came up with:
<img width="166" alt="screen shot 2017-11-14 at 1 16 35 am" src="https://user-images.githubusercontent.com/11262741/32765751-f7e77402-c8d9-11e7-8257-9bf18772185c.png">
<img width="172" alt="screen shot 2017-11-14 at 1 16 05 am" src="https://user-images.githubusercontent.com/11262741/32765746-f084fd88-c8d9-11e7-9a79-c17b08304b40.png">
 I think it's important to keep the icon close to the existing Shifty icon so it still is recognizable as the same app. This new icon would be shown in the menu bar in place of the current one when Night Shift is off and when the user enables this feature in Preferences.

Right now, I'm leaning towards the first one. Let me know what you think. @villiansv @vinkla @onedr0p @svh1985

**Comment by villiansv** [comment]
@thompsonate I personally thing that the second one is a bit easier to see at a glance, but either would work.

**Comment by thompsonate** [comment]
I decided to go with the second one since that's what everyone I asked preferred.
