### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ericcirone** [thompsonate/Shifty#63]
I've had shifty running for 9 days, the total uptime of my iMac and I just noticed the computer running sluggish. I checked Activity Monitor and Shifty was consuming 2.8GB of memory.

**Comment by basalphenaar** [comment]
Yes, also just noticed this. It was consuming about 3GB of memory, after restarting it it was just 12MB.

**Comment by thompsonate** [comment]
Sorry I've been unresponsive on this. It definitely shouldn't be taking up that much memory. If anyone would like to help me figure out what's causing this, that'd be great!

**Comment by ericcirone** [comment]
I only saw this after first updating to Mojave and the latest version. I had also to automatically put on dark mode at sunset as well. I have since turned off that feature and haven’t seen shifty spike in memory. Might be a good place to start.

**Comment by choco** [comment]
I'm not sure this is the cause, but just from a really quick run I see some leaks related to ScriptingBridge.
<img width="414" alt="screen shot 2018-11-12 at 13 38 41" src="https://user-images.githubusercontent.com/85527/48348076-85cff180-e680-11e8-93fc-2d5567b32d77.png">
I don't think there's something wrong with the code at first glance, but it may be better to take a look at other swift projects using ScriptingBridge and see what they do different.
