### ISSUE TITLE
Scheduled Dark/Light Mode - theme not switched to the correct one on Shifty launch

### ISSUE THREAD

**Issue by maciejtarmas** [thompsonate/Shifty#69]
Hi,

After updating to macOS 10.14.3, my Mac came up with Light Mode enabled after reboot.

It was already supposed to go into scheduled Night Shift, so I expected the theme to change to Dark when Shifty launched.

The theme didn't change though. It only did switch over to Dark Mode when I went into Shifty and disabled Night Shift before reenabling it again.

I can easily reproduce this by quitting Shifty, switching the macOS theme to the opposite mode, and relaunching Shifty. It should check at startup if the theme is set according to the prefs (Scheduled Dark Mode) and if not, switch the theme to the correct one. It fails to do so and requires toggling Night Shift off and on.

macOS 10.14.3
Shifty 1.0.2
Time zone: CET
![shifty_launch 2019-01-22 21_48_42](https://user-images.githubusercontent.com/3435387/51564466-ac37b780-1e8f-11e9-9a2b-39b3987e4473.gif)

**Comment by maciejtarmas** [comment]
Thanks!

I'll help you out with a Polish translation some time next month.

If you remember Growl (RIP), I was responsible for their complete Polish UI, so I have some experience in this field ;)

**Comment by thompsonate** [comment]
Sounds great! You can contribute here: https://crowdin.com/project/shifty/pl#
