### ISSUE TITLE
Make changes in color temperature immediate

### ISSUE THREAD

**Issue by oakif** [thompsonate/Shifty#72]
When a color temperature change is invoked via Shifty, the color temperature seems to change very gradually. In contrast, the changes performed via System Preferences seems to be instantaneous, so I'm assuming Shifty is making the changes gradual.

Would it be possible to mimic the system behavior, where these changes in color temperature are (almost) instantaneous? It gives a better idea of what color temperature I would like, especially when modifying it with shortcuts.

**Comment by thompsonate** [comment]
The slider in System Preferences must be doing something special. I'd say this fairly low priority, but I'll try to see if it's feasible.

**Comment by oakif** [comment]
I see—I was hoping Shifty was the one doing something special! Thank you for your reply.

**Comment by thompsonate** [comment]
No, I didn't do it this way intentionally. Night Shift is a private framework so it isn't really documented at all. If System Preferences does it, though, it should be possible.
