### ISSUE TITLE
Localization 

### ISSUE THREAD

**Issue by KovalevArtem** [thompsonate/Shifty#73]
I am saddened that the program is in English only.
I suggest to localize the program.
I am ready to assist in the translation into Russian.
(For example, you can use the service Crowdin or any other. Crowdin is free for Open source projects.)

**Comment by thompsonate** [comment]
I have good news for you! Shifty has already been translated into Russian and will be released in an update shortly.

If notice any issues with the translations, please contribute [here](http://shifty.natethompson.io/translate).
