### ISSUE TITLE
Bug: web browsers sometimes reopen on their own when Website Shifting is enabled

### ISSUE THREAD

**Issue by terabyte128** [thompsonate/Shifty#74]
When I quit a web browser using Cmd+Q or the Quit option from the menu, the browser sometimes immediately reopens (I'd estimate around 70% of the time). This only seems to happen when Shifty is running _and_ when the "Website Shifting" feature is enabled.

I've tested this with Chrome, Safari and Vivaldi.

**Comment by choco** [comment]
This was a known issue with Chrome (and probably Vivaldi since that’s the same) but it should have been fixed... Can you check the version of Shifty you have installed?
You’re also mentioning Safari, are you sure you’re able to reproduce the issue with that browser?

**Comment by terabyte128** [comment]
Yes, I tested it with Safari as well. But the updated version fixed this, sorry I should have checked that first!
