### ISSUE TITLE
seems that shifty is undownloadable

### ISSUE THREAD

**Issue by semiopat** [thompsonate/Shifty#79]
Hello
I try to download Shifty but the button on the website does nothing, and the gihub master is not compiled ?

**Comment by choco** [comment]
Hi, the download is working correctly for me. Can you paste the address where you are trying to download the app? (and also the download button address)
Master branch isn't automatically compiled, but the current version is on par with the master branch.

In the mean time you can download Shifty from the releases section here on GitHub https://github.com/thompsonate/Shifty/releases

**Comment by semiopat** [comment]
The button at this adress: https://shifty.natethompson.io/en/ (which is the link I had from the post I read about Shifty). And sorry, I didn't know nor see there's a release branch on GitHub (not familiar with it). Now it's downloaded and installed. Thanks.

**Comment by choco** [comment]
Glad you were able to download it in the end! I don't see anything wrong on the download page, the html is pretty straight forward and works for me and others, so I'm not sure if there's something going on with your browser. I'll close this in the mean time.
