### ISSUE TITLE
Not enabling automatically

### ISSUE THREAD

**Issue by FezVrasta** [thompsonate/Shifty#8]
Since I installed this app night shift is not enabling itself automatically at evening. I'm not sure if it's related to this app, I uninstalled it to see if it's going to work properly tomorrow.

Are you aware of similar problems?

**Comment by thompsonate** [comment]
I have noticed Shifty interfering with the automatic schedule. I've been taking a bit of a break from development on Shifty, but hopefully I'll be able to fix this issue soon. Right now, it's at the top of the list of things that need work in the app.

There is, however, a scenario where Shifty would block Night Shift from enabling automatically. If you use Shifty to temporarily disable Night Shift, then it will keep it disabled until the specified time period is up or the current app is switched to one that is not set to disable. If Night Shift is not enabled after the time period expires or the current app is switched, then that's definitely an issue. I haven't noticed any problems with this though. 

Shifty will not interfere with the schedule as long as it isn't running. If you've experienced problems with Night Shift while Shifty is not running, that's definitely Apple's problem.

**Comment by thompsonate** [comment]
Closing this issue because I fixed something that may have been causing your issue. Look for an update soon and if you're still having problems, please let me know.
