### ISSUE TITLE
Shifty inhibits Night Shift on sunset 

### ISSUE THREAD

**Issue by petervannes** [thompsonate/Shifty#83]
When Shifty is active and Mac OS 10.14.6 Nightshift is scheduled from Sunset to Sunrise, Nightshift is inhibited to start. Also taking these steps shows that Shifty interferes the Mac OS Nightshift settings.

* Configure MacOS NightShift to schedule from sunset to sunrise and uncheck the manual checkbox.
* Start shifty at a time between sunset and sunrise. The screen will get somewhat warmer.
* Set NightShift Schedule to Custom, the screen gets a much warmer color.

**Comment by choco** [comment]
I can't reproduce this, but there was/is an issue with macOS 10.14.6 #86 so it may be related. Please try the build in that post and if you can still reproduce the issue I'll reopen this thread.
