### ISSUE TITLE
macOS Catalina prevents Shifty from running without Sandboxing

### ISSUE THREAD

**Issue by Sam-Spencer** [thompsonate/Shifty#84]
As of macOS Catalina (currently in beta 1) and its new security requirements, Shifty will not run unless it is sandboxed and signed. Unfortunately, sandboxing Swifty causes other unintended issues that prevent the app from working properly... looks like its going to take some work to get it fixed :/.

**Comment by saagarjha** [comment]
macOS Catalina should only require Notarization as far as I’m aware. I don’t think Apple has started enforcing sandboxing for all macOS apps?

**Comment by Sam-Spencer** [comment]
That looks to be the case, actually:

> Mac apps, installer packages, and kernel extensions that are signed with Developer ID must also be notarized by Apple in order to run on macOS Catalina.

However, I found that when running the project on Catalina it crashes at `main` and enabling sandboxing allowed it to continue. Is it possible this is just an issue with the beta itself and not Shifty?

**Comment by choco** [comment]
I suspect this was the same issue as #86 so I will close this for now.
