### ISSUE TITLE
Feature request: f.lux Darkroom color effect

### ISSUE THREAD

**Issue by skyfaller** [thompsonate/Shifty#85]
I realize this may not be possible through Night Shift, and I apologize if it is out of scope of the Shifty project. Still, I would love to use an open source f.lux alternative, and the only feature keeping me on f.lux is the Darkroom mode, which is just so cool!

Darkroom mode inverts the color scheme, and makes the screen monochrome with the only two colors (various shades of) red and black. If blue light harms your sleep at night, surely completely eliminating blue light would be ideal? :D It's great late at night if you want to do something on the computer without ruining your night vision. Also it looks like you're working in a submarine, how bad ass is that?

I suspect you might even be able to out-do f.lux's Darkroom by using macOS dark mode instead of inverting the color scheme, once enough programs and websites support dark mode. I currently avoid dark mode on everything because it will interfere with Darkroom.

**Comment by choco** [comment]
Unfortunately this is probably outside the scope of the app. Shifty uses the included functionality in macOS to change the display colours; f.lux uses custom color profiles, so it has a lot more flexibility (and obviously required more work, researching, testing).

You could try to enable the "Scheduled dark mode" option in Shifty and see if it's enough for your use case (It enables dark mode when night shift kicks in).

**Comment by r4dixx** [comment]
In Catalina, system color tint presets are here, including a greyscale one. Maybe this might be a fit? This would be awesome to have such option. Triggered after a certain time or even (and maybe I'm overthinking it) linked to the new Screen Time feature. What do you think?
