### ISSUE TITLE
Quits when opening preferences and can't be open again

### ISSUE THREAD

**Issue by daletman** [thompsonate/Shifty#88]
- I'm on macOS 10.14.6 and using Shifty 1.1.1 on a 2018 MacBook Pro 15" with it's lid closed (True Tone not available) and 2 4K Monitors connected
- Today I opened Shifty (installed via Homebrew) and clicked in the preferences window "Scheduled -> Custom"
- The App crashed and I couldn't open it again even after removing it via Homebrew or CleanMyMac 3 and reinstalling via Homebrew
- After deleting it, logging out and in again and installing it via a download from the webpage the app launched again
- I clicked on Preferences and the App crashed and doesn't launch even after deleting via CleanMyMac 3 and installing it again from the websites download

What can I check to make it run again? I had send crash reports turned off.

**Comment by choco** [comment]
Check the build here https://github.com/thompsonate/Shifty/issues/86#issuecomment-514153116
this is probably the same issue.
